<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tahun_akademik extends MY_Controller {

    
    
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tahun_akademik_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'tahun_akademik/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'tahun_akademik/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'tahun_akademik/index.html';
            $config['first_url'] = base_url() . 'tahun_akademik/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Tahun_akademik_model->total_rows($q);
        $tahun_akademik = $this->Tahun_akademik_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'tahun_akademik_data' => $tahun_akademik,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('header');
        $this->load->view('tahun_akademik_list', $data);
        $this->load->view('footer');
    }

    public function read($id) 
    {
        $row = $this->Tahun_akademik_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'tahun' => $row->tahun,
	    );
            $this->load->view('header');
            $this->load->view('tahun_akademik_read', $data);
            $this->load->view('footer');
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tahun_akademik'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('tahun_akademik/create_action'),
	    'id' => set_value('id'),
	    'tahun' => set_value('tahun'),
	);

        $this->load->view('header');
        $this->load->view('tahun_akademik_form', $data);
        $this->load->view('footer');
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'tahun' => $this->input->post('tahun',TRUE),
	    );

            $this->Tahun_akademik_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('tahun_akademik'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tahun_akademik_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('tahun_akademik/update_action'),
		'id' => set_value('id', $row->id),
		'tahun' => set_value('tahun', $row->tahun),
	    );
            $this->load->view('header');
            $this->load->view('tahun_akademik_form', $data);
            $this->load->view('footer');
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tahun_akademik'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'tahun' => $this->input->post('tahun',TRUE),
	    );

            $this->Tahun_akademik_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('tahun_akademik'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tahun_akademik_model->get_by_id($id);

        if ($row) {
            $this->Tahun_akademik_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('tahun_akademik'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tahun_akademik'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('tahun', 'tahun', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Tahun_akademik.php */
/* Location: ./application/controllers/Tahun_akademik.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-27 14:36:37 */
/* http://harviacode.com */